name: "📦 Pre-Release"

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
      name: Pre-release notes
      runs-on: ubuntu-latest
      steps:
        - name: Pre-release notes generation
          uses: "marvinpinto/action-automatic-releases@latest"
          with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            prerelease: true
            automatic_release_tag: latest